import type { AppData } from './types';

export const defaultData: AppData = {
  meals: [
    {
      id: 'spaghetti-bol',
      name: 'Spaghetti Bolognaise',
      ingredients: [
        { id: 'sb-1', category: 'Meat', item: 'Mince', quantity: '500g' },
        { id: 'sb-2', category: 'Carbs', item: 'Spaghetti', quantity: '1 pack' },
        { id: 'sb-3', category: 'Pantry', item: 'Tinned tomatoes', quantity: '2 cans' },
        { id: 'sb-4', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'sb-5', category: 'Vegetables', item: 'Garlic', quantity: '2 cloves' },
      ],
    },
    {
      id: 'chicken-stir-fry',
      name: 'Chicken Stir Fry',
      ingredients: [
        { id: 'csf-1', category: 'Meat', item: 'Chicken breast/strips', quantity: '500g' },
        { id: 'csf-2', category: 'Vegetables', item: 'Carrots', quantity: '2' },
        { id: 'csf-3', category: 'Vegetables', item: 'Broccoli', quantity: '1 head' },
        { id: 'csf-4', category: 'Pantry', item: 'Soy sauce', quantity: '3 tbsp' },
        { id: 'csf-5', category: 'Carbs', item: 'Rice', quantity: '2 cups' },
      ],
    },
    {
      id: 'pork-chops',
      name: 'Pork Chops, Mash & Broccoli',
      ingredients: [
        { id: 'pc-1', category: 'Meat', item: 'Pork chops', quantity: '1–1.2 kg' },
        { id: 'pc-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'pc-3', category: 'Vegetables', item: 'Broccoli', quantity: '1 head' },
      ],
    },
    {
      id: 'chicken-strips-chips',
      name: 'Air Fryer Chicken Strips & Chips',
      ingredients: [
        { id: 'ac-1', category: 'Meat', item: 'Frozen chicken strips', quantity: '1 bag', notes: 'Lazy day' },
        { id: 'ac-2', category: 'Carbs', item: 'Chips', quantity: '1 bag' },
      ],
    },
    {
      id: 'mushroom-mince-pasta',
      name: 'Mushroom & Mince Pasta',
      ingredients: [
        { id: 'mmp-1', category: 'Meat', item: 'Mince', quantity: '500g' },
        { id: 'mmp-2', category: 'Vegetables', item: 'Mushrooms', quantity: '250g' },
        { id: 'mmp-3', category: 'Carbs', item: 'Pasta', quantity: '1 pack' },
        { id: 'mmp-4', category: 'Pantry', item: 'Tomato paste', quantity: '1 tube' },
        { id: 'mmp-5', category: 'Vegetables', item: 'Onions', quantity: '1' },
      ],
    },
    {
      id: 'bbq-chicken',
      name: 'BBQ Oven Chicken + Potatoes + Broccoli',
      ingredients: [
        { id: 'bc-1', category: 'Meat', item: 'Chicken braai pack', quantity: '1–2 packs' },
        { id: 'bc-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'bc-3', category: 'Vegetables', item: 'Broccoli', quantity: '1 head' },
        { id: 'bc-4', category: 'Pantry', item: 'BBQ sauce', quantity: '1 bottle' },
      ],
    },
    {
      id: 'pork-fried-rice',
      name: 'Pork Fried Rice',
      ingredients: [
        { id: 'pfr-1', category: 'Meat', item: 'Pork strips/chunks', quantity: '500g' },
        { id: 'pfr-2', category: 'Carbs', item: 'Rice', quantity: '2 cups' },
        { id: 'pfr-3', category: 'Vegetables', item: 'Peppers', quantity: '2' },
        { id: 'pfr-4', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'pfr-5', category: 'Pantry', item: 'Soy sauce', quantity: '3 tbsp' },
      ],
    },
    {
      id: 'burgers-chips',
      name: 'Burgers & Chips',
      ingredients: [
        { id: 'bch-1', category: 'Meat', item: 'Burger patties', quantity: '6' },
        { id: 'bch-2', category: 'Carbs', item: 'Burger buns', quantity: '1 pack' },
        { id: 'bch-3', category: 'Carbs', item: 'Chips', quantity: '1 bag' },
        { id: 'bch-4', category: 'Vegetables', item: 'Lettuce', quantity: '1 head' },
        { id: 'bch-5', category: 'Vegetables', item: 'Tomatoes', quantity: '2' },
      ],
    },
    {
      id: 'chicken-potato-curry',
      name: 'Chicken & Potato Curry',
      ingredients: [
        { id: 'cpc-1', category: 'Meat', item: 'Chicken pieces', quantity: '1.5 kg' },
        { id: 'cpc-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'cpc-3', category: 'Pantry', item: 'Coconut milk', quantity: '2 cans' },
        { id: 'cpc-4', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'cpc-5', category: 'Pantry', item: 'Spices', quantity: 'Variety' },
      ],
    },
    {
      id: 'mince-potato-hash',
      name: 'Mince & Potato Hash',
      ingredients: [
        { id: 'mph-1', category: 'Meat', item: 'Mince', quantity: '500g' },
        { id: 'mph-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'mph-3', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'mph-4', category: 'Vegetables', item: 'Carrots', quantity: '2' },
      ],
    },
    {
      id: 'chicken-wraps',
      name: 'Chicken Wraps',
      ingredients: [
        { id: 'cw-1', category: 'Meat', item: 'Chicken breast/strips', quantity: '500g' },
        { id: 'cw-2', category: 'Carbs', item: 'Wraps', quantity: '1 pack' },
        { id: 'cw-3', category: 'Vegetables', item: 'Lettuce', quantity: '1 head' },
        { id: 'cw-4', category: 'Vegetables', item: 'Tomatoes', quantity: '4' },
        { id: 'cw-5', category: 'Vegetables', item: 'Cucumber', quantity: '1' },
      ],
    },
    {
      id: 'sandwiches-noodles',
      name: 'Sandwiches / Noodles',
      ingredients: [
        { id: 'sn-1', category: 'Carbs', item: 'Bread', quantity: '1 loaf' },
        { id: 'sn-2', category: 'Carbs', item: 'Instant noodles', quantity: '2 packs' },
      ],
    },
    {
      id: 'pork-sausage-bake',
      name: 'Pork Sausage & Potato Bake',
      ingredients: [
        { id: 'psb-1', category: 'Meat', item: 'Pork sausages', quantity: '1–1.5 kg' },
        { id: 'psb-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'psb-3', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'psb-4', category: 'Pantry', item: 'Tomato sauce', quantity: '1 bottle' },
      ],
    },
    {
      id: 'mince-stuffed-peppers',
      name: 'Mince Stuffed Peppers',
      ingredients: [
        { id: 'msp-1', category: 'Meat', item: 'Mince', quantity: '500g' },
        { id: 'msp-2', category: 'Vegetables', item: 'Peppers', quantity: '3–4' },
        { id: 'msp-3', category: 'Pantry', item: 'Tomato sauce', quantity: '1 bottle' },
        { id: 'msp-4', category: 'Vegetables', item: 'Onions', quantity: '1' },
        { id: 'msp-5', category: 'Carbs', item: 'Rice', quantity: '1 cup' },
      ],
    },
    {
      id: 'garlic-chicken-tray-bake',
      name: 'Garlic Chicken Tray Bake',
      ingredients: [
        { id: 'gct-1', category: 'Meat', item: 'Chicken', quantity: '1–1.5 kg' },
        { id: 'gct-2', category: 'Vegetables', item: 'Potatoes', quantity: '1 kg' },
        { id: 'gct-3', category: 'Vegetables', item: 'Garlic', quantity: '1 bulb' },
        { id: 'gct-4', category: 'Vegetables', item: 'Broccoli', quantity: '1 head' },
        { id: 'gct-5', category: 'Pantry', item: 'Cooking oil', quantity: '2 tbsp' },
      ],
    },
  ],
  mealPlan: [
    { week: 1, day: 1, mealId: 'spaghetti-bol', note: 'Cook' },
    { week: 1, day: 2, mealId: 'spaghetti-bol', note: 'Leftovers' },
    { week: 1, day: 3, mealId: 'chicken-stir-fry', note: 'Cook' },
    { week: 1, day: 4, mealId: 'chicken-stir-fry', note: 'Leftovers' },
    { week: 1, day: 5, mealId: 'pork-chops', note: 'Cook' },
    { week: 1, day: 6, mealId: 'pork-chops', note: 'Leftovers' },
    { week: 1, day: 7, mealId: 'chicken-strips-chips', note: 'Lazy Day' },
    { week: 2, day: 8, mealId: 'mushroom-mince-pasta', note: 'Cook' },
    { week: 2, day: 9, mealId: 'mushroom-mince-pasta', note: 'Leftovers' },
    { week: 2, day: 10, mealId: 'bbq-chicken', note: 'Cook' },
    { week: 2, day: 11, mealId: 'bbq-chicken', note: 'Leftovers' },
    { week: 2, day: 12, mealId: 'pork-fried-rice', note: 'Cook' },
    { week: 2, day: 13, mealId: 'pork-fried-rice', note: 'Leftovers' },
    { week: 2, day: 14, mealId: 'burgers-chips', note: 'Treat' },
    { week: 3, day: 15, mealId: 'chicken-potato-curry', note: 'Cook' },
    { week: 3, day: 16, mealId: 'chicken-potato-curry', note: 'Leftovers' },
    { week: 3, day: 17, mealId: 'mince-potato-hash', note: 'Cook' },
    { week: 3, day: 18, mealId: 'mince-potato-hash', note: 'Leftovers' },
    { week: 3, day: 19, mealId: 'chicken-wraps', note: 'Cook' },
    { week: 3, day: 20, mealId: 'chicken-wraps', note: 'Leftovers' },
    { week: 3, day: 21, mealId: 'sandwiches-noodles', note: 'Lazy Day' },
    { week: 4, day: 22, mealId: 'pork-sausage-bake', note: 'Cook' },
    { week: 4, day: 23, mealId: 'pork-sausage-bake', note: 'Leftovers' },
    { week: 4, day: 24, mealId: 'mince-stuffed-peppers', note: 'Cook' },
    { week: 4, day: 25, mealId: 'mince-stuffed-peppers', note: 'Leftovers' },
    { week: 4, day: 26, mealId: 'garlic-chicken-tray-bake', note: 'Cook' },
    { week: 4, day: 27, mealId: 'garlic-chicken-tray-bake', note: 'Leftovers' },
  ],
  weekShops: [
    {
      week: 1,
      items: [
        { id: 'w1-1', category: 'Meat', item: 'Mince', quantity: '1.5 kg', checked: false },
        { id: 'w1-2', category: 'Meat', item: 'Chicken breast/strips', quantity: '1 kg', checked: false },
        { id: 'w1-3', category: 'Meat', item: 'Pork chops', quantity: '1–1.2 kg', checked: false },
        { id: 'w1-4', category: 'Meat', item: 'Frozen chicken strips', quantity: '1 bag', notes: 'Lazy day', checked: false },
        { id: 'w1-5', category: 'Vegetables', item: 'Potatoes', quantity: '4 kg', checked: false },
        { id: 'w1-6', category: 'Vegetables', item: 'Broccoli', quantity: '3 heads', checked: false },
        { id: 'w1-7', category: 'Vegetables', item: 'Carrots', quantity: '1 kg', checked: false },
        { id: 'w1-8', category: 'Vegetables', item: 'Onions', quantity: '1 kg', checked: false },
        { id: 'w1-9', category: 'Vegetables', item: 'Garlic', quantity: '1 bulb', checked: false },
        { id: 'w1-10', category: 'Carbs', item: 'Spaghetti', quantity: '2 packs', checked: false },
        { id: 'w1-11', category: 'Carbs', item: 'Rice', quantity: '2 kg', checked: false },
        { id: 'w1-12', category: 'Carbs', item: 'Chips', quantity: '1–2 bags', checked: false },
        { id: 'w1-13', category: 'Pantry', item: 'Tinned tomatoes', quantity: '4–6 cans', notes: 'Monthly', checked: false },
        { id: 'w1-14', category: 'Pantry', item: 'Cooking oil', quantity: '1 bottle', notes: 'Monthly', checked: false },
        { id: 'w1-15', category: 'Pantry', item: 'Soy sauce', quantity: '1 bottle', notes: 'Monthly', checked: false },
        { id: 'w1-16', category: 'Pantry', item: 'Spices', quantity: 'Variety', notes: 'Monthly', checked: false },
      ],
    },
    {
      week: 2,
      items: [
        { id: 'w2-1', category: 'Meat', item: 'Mince', quantity: '1 kg', checked: false },
        { id: 'w2-2', category: 'Meat', item: 'Chicken braai pack', quantity: '1–2 packs', checked: false },
        { id: 'w2-3', category: 'Meat', item: 'Pork strips/chunks', quantity: '500g–1kg', checked: false },
        { id: 'w2-4', category: 'Meat', item: 'Burger patties', quantity: '6', checked: false },
        { id: 'w2-5', category: 'Vegetables', item: 'Potatoes', quantity: '3 kg', checked: false },
        { id: 'w2-6', category: 'Vegetables', item: 'Broccoli', quantity: '2 heads', checked: false },
        { id: 'w2-7', category: 'Vegetables', item: 'Peppers', quantity: '3–4', checked: false },
        { id: 'w2-8', category: 'Vegetables', item: 'Onions', quantity: '1 kg', checked: false },
        { id: 'w2-9', category: 'Carbs', item: 'Burger buns', quantity: '1 pack', checked: false },
        { id: 'w2-10', category: 'Carbs', item: 'Wraps', quantity: '1 pack', notes: 'Optional', checked: false },
        { id: 'w2-11', category: 'Pantry', item: 'BBQ sauce', quantity: '1 bottle', checked: false },
        { id: 'w2-12', category: 'Pantry', item: 'Tomato paste', quantity: '1 tube', checked: false },
      ],
    },
    {
      week: 3,
      items: [
        { id: 'w3-1', category: 'Meat', item: 'Chicken pieces', quantity: '1.5 kg', checked: false },
        { id: 'w3-2', category: 'Meat', item: 'Mince', quantity: '1 kg', checked: false },
        { id: 'w3-3', category: 'Vegetables', item: 'Potatoes', quantity: '3 kg', checked: false },
        { id: 'w3-4', category: 'Vegetables', item: 'Broccoli', quantity: '2 heads', checked: false },
        { id: 'w3-5', category: 'Vegetables', item: 'Spinach', quantity: '1 bag', notes: 'Optional', checked: false },
        { id: 'w3-6', category: 'Vegetables', item: 'Carrots', quantity: '1 kg', checked: false },
        { id: 'w3-7', category: 'Vegetables', item: 'Onions', quantity: '1 kg', checked: false },
        { id: 'w3-8', category: 'Pantry', item: 'Coconut milk', quantity: '2–3 cans', checked: false },
        { id: 'w3-9', category: 'Carbs', item: 'Wraps', quantity: '1 pack', checked: false },
        { id: 'w3-10', category: 'Vegetables', item: 'Lettuce', quantity: '1 head', checked: false },
        { id: 'w3-11', category: 'Vegetables', item: 'Tomatoes', quantity: '4–6', checked: false },
        { id: 'w3-12', category: 'Vegetables', item: 'Cucumber', quantity: '1–2', checked: false },
      ],
    },
    {
      week: 4,
      items: [
        { id: 'w4-1', category: 'Meat', item: 'Pork sausages', quantity: '1–1.5 kg', checked: false },
        { id: 'w4-2', category: 'Meat', item: 'Mince', quantity: '1 kg', checked: false },
        { id: 'w4-3', category: 'Meat', item: 'Chicken', quantity: '1–1.5 kg', checked: false },
        { id: 'w4-4', category: 'Vegetables', item: 'Potatoes', quantity: '3 kg', checked: false },
        { id: 'w4-5', category: 'Vegetables', item: 'Peppers', quantity: '3–4', checked: false },
        { id: 'w4-6', category: 'Vegetables', item: 'Broccoli', quantity: '2 heads', checked: false },
        { id: 'w4-7', category: 'Vegetables', item: 'Onions', quantity: '1 kg', checked: false },
        { id: 'w4-8', category: 'Pantry', item: 'Tomato sauce', quantity: '1 bottle', checked: false },
        { id: 'w4-9', category: 'Vegetables', item: 'Garlic', quantity: '1 bulb', checked: false },
      ],
    },
  ],
};
